name: Node.js CI

on: 
    push
      branches: [ main ]
    pull_request
      branches: [ main ]
      
      
 jobs:
    build:
      
      runs-on: [ubuntu-latest, windows-2016]
      
      strategy:
        matrix:
          node_version: [8.x, 10.x]
          
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js matrix ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with 
              node-version: {{ matrix.node-version }}
           - run |
               npm install
               npm test
               
             env:
               CI: true
               
               
              
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

